"""schema updates — session columns, chat messages

Revision ID: 08a150a30733
Revises: 4ee09ceceb93
Create Date: 2026-03-26 03:05:18.202751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08a150a30733'
down_revision: Union[str, None] = '4ee09ceceb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_messages_funnel_created', 'chat_messages', ['funnel_id', 'created_at'], unique=False)
    op.create_index('idx_chat_messages_funnel_id', 'chat_messages', ['funnel_id'], unique=False)
    op.create_index('idx_chat_messages_user_id', 'chat_messages', ['user_id'], unique=False)
    op.add_column('funnel_projects', sa.Column('session_id', sa.Text(), nullable=True, comment='Claude Agent SDK session ID. Tracks the ongoing user ↔ funnel_builder chat session only. NOT orchestration state — that lives on workflow_runs.langgraph_thread_id. Stored on first builder open. Resumed on return to keep chat context. Null until user first opens the builder for this funnel.'))
    op.add_column('funnel_projects', sa.Column('session_summary', sa.Text(), nullable=True, comment='Compressed summary of older chat history injected into agent context instead of raw messages. Updated periodically. Keeps token cost flat as conversation grows.'))
    op.alter_column('workflow_runs', 'langgraph_thread_id',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='v2 — LangGraph AsyncPostgresSaver thread_id for checkpoint resume',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_runs', 'langgraph_thread_id',
               existing_type=sa.TEXT(),
               comment='v2 — LangGraph AsyncPostgresSaver thread_id for checkpoint resume',
               existing_nullable=True)
    op.drop_column('funnel_projects', 'session_summary')
    op.drop_column('funnel_projects', 'session_id')
    op.drop_index('idx_chat_messages_user_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_funnel_id', table_name='chat_messages')
    op.drop_index('idx_chat_messages_funnel_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
