"""initial schema

Revision ID: 4ee09ceceb93
Revises: 
Create Date: 2026-03-23 15:25:08.570534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ee09ceceb93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('plan', sa.Enum('free', 'standard', 'pro', 'agency', name='user_plan'), server_default='free', nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.Text(), nullable=True),
    sa.Column('stripe_subscription_id', sa.Text(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clerk_id')
    )
    op.create_index('idx_users_clerk_id', 'users', ['clerk_id'], unique=True)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('github', 'ghl', 'meta_ads', 'google_ads', 'klaviyo', 'active_campaign', 'mailchimp', 'elevenlabs', 'kling', 'hubspot', 'clickfunnels', 'zoho_crm', name='integration_provider'), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=False, comment='Fernet-encrypted. Never store plaintext. Decrypt only server-side.'),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True, comment='Fernet-encrypted refresh token. Required for GHL, Meta Ads (tokens expire).'),
    sa.Column('account_id', sa.Text(), nullable=True, comment='Provider account ID. GHL: location_id. Meta: ad_account_id. GitHub: username.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Provider-specific extras. GHL: {pipeline_id, tag}. Meta: {pixel_id}. GitHub: {default_branch}.'),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True, comment='null = token does not expire (GitHub). Set for GHL, Meta Ads.'),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integrations_user_id', 'integrations', ['user_id'], unique=False)
    op.create_index('idx_integrations_user_provider_unique', 'integrations', ['user_id', 'provider'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspaces_owner', 'workspaces', ['owner_user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=False, comment='Denormalised from intake_data for fast filtering and agent context building'),
    sa.Column('status', sa.Enum('active', 'archived', 'deleted', name='offer_status'), server_default='active', nullable=False),
    sa.Column('intake_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full 19-step wizard answers. Pydantic IntakeData schema. Never mutated after creation.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_offers_user_created', 'offers', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_offers_user_id', 'offers', ['user_id'], unique=False)
    op.create_index('idx_offers_user_status', 'offers', ['user_id', 'status'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), server_default='member', nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workspace_members_unique', 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    op.create_index('idx_workspace_members_user', 'workspace_members', ['user_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Denormalised for O(1) ownership checks'),
    sa.Column('workflow_type', sa.Enum('funnel_only', 'full_gtm', 'ad_campaign', 'email_only', 'research_only', name='workflow_type'), server_default='funnel_only', nullable=False),
    sa.Column('active_agents', postgresql.ARRAY(sa.String()), server_default=sa.text("ARRAY['analyst','copywriter','assembler']"), nullable=False, comment='Which agent nodes run in this workflow. Drives job creation.'),
    sa.Column('status', sa.Enum('pending', 'running', 'awaiting_approval', 'done', 'error', 'cancelled', name='workflow_status'), server_default='pending', nullable=False),
    sa.Column('hil_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='v2 — payload shown to user at HIL pause point'),
    sa.Column('hil_checkpoint', sa.Text(), nullable=True, comment='v2 — which LangGraph node is paused e.g. copywriter'),
    sa.Column('langgraph_thread_id', sa.Text(), nullable=True, comment='v2 — LangGraph AsyncPostgresSaver thread_id for checkpoint resume'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_runs_offer_id', 'workflow_runs', ['offer_id'], unique=False)
    op.create_index('idx_workflow_runs_user_id', 'workflow_runs', ['user_id'], unique=False)
    op.create_index('idx_workflow_runs_user_status', 'workflow_runs', ['user_id', 'status'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.Enum('analyst', 'copywriter', 'funnel_builder', 'media_buyer', 'email', 'image', 'video', 'audio', name='agent_type'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Increments when this agent is re-run for the same workflow_run'),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_outputs_offer_agent', 'agent_outputs', ['offer_id', 'agent_type'], unique=False)
    op.create_index('idx_agent_outputs_offer_id', 'agent_outputs', ['offer_id'], unique=False)
    op.create_index('idx_agent_outputs_run_agent_version', 'agent_outputs', ['workflow_run_id', 'agent_type', 'version'], unique=False)
    op.create_index('idx_agent_outputs_run_id', 'agent_outputs', ['workflow_run_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.Text(), nullable=False, comment='image | video | audio'),
    sa.Column('r2_key', sa.Text(), nullable=False, comment='R2 object key. Pattern: assets/{offer_id}/{asset_type}/{uuid}.{ext}'),
    sa.Column('public_url', sa.Text(), nullable=False, comment='R2 public URL constructed from r2_key at upload time.'),
    sa.Column('provider', sa.Text(), nullable=False, comment='Which service generated this. nano-banana | dalle | kling | runwayml | elevenlabs'),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Prompt + params used for generation. Enables regeneration with same settings.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assets_offer_id', 'assets', ['offer_id'], unique=False)
    op.create_index('idx_assets_offer_type', 'assets', ['offer_id', 'asset_type'], unique=False)
    op.create_index('idx_assets_user_id', 'assets', ['user_id'], unique=False)
    op.create_index('idx_assets_workflow_run_id', 'assets', ['workflow_run_id'], unique=False)
    op.create_table('funnels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=True, comment='Which run generated this funnel. null = manually created (v2).'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Denormalised for O(1) ownership checks'),
    sa.Column('name', sa.Text(), nullable=False, comment='e.g. 90-Day Body Transformation — VSL Funnel'),
    sa.Column('funnel_type', sa.Enum('vsl', 'lead_magnet', 'webinar', 'product_launch', 'book', 'application', name='funnel_type'), server_default='vsl', nullable=False),
    sa.Column('theme', sa.Text(), server_default='bold-dark', nullable=False, comment='Theme slug. bold-dark | clean-pro | warm-story | power-red | trust-blue | minimal'),
    sa.Column('status', sa.Enum('draft', 'generating', 'ready', 'error', name='funnel_status'), server_default='draft', nullable=False),
    sa.Column('published_url', sa.Text(), nullable=True, comment='v2 — Cloudflare Pages live URL after deployment. null in MVP.'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='v2 — timestamp of last Cloudflare Pages deployment.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funnels_offer_id', 'funnels', ['offer_id'], unique=False)
    op.create_index('idx_funnels_user_id', 'funnels', ['user_id'], unique=False)
    op.create_index('idx_funnels_user_status', 'funnels', ['user_id', 'status'], unique=False)
    op.create_index('idx_funnels_workflow_run_id', 'funnels', ['workflow_run_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False, comment='Denormalised for direct offer-level job queries'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Denormalised for O(1) ownership checks'),
    sa.Column('agent_type', sa.Enum('analyst', 'copywriter', 'funnel_builder', 'media_buyer', 'email', 'image', 'video', 'audio', name='agent_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', 'skipped', name='job_status'), server_default='pending', nullable=False),
    sa.Column('progress', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='Append-only array of {stage, message, ts, done}. Never overwrite.'),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_run_agent_unique', 'jobs', ['workflow_run_id', 'agent_type'], unique=True)
    op.create_index('idx_jobs_user_id', 'jobs', ['user_id'], unique=False)
    op.create_index('idx_jobs_user_status', 'jobs', ['user_id', 'status'], unique=False)
    op.create_index('idx_jobs_workflow_run_id', 'jobs', ['workflow_run_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False, comment='Denormalised for offer-level export queries'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('export_type', sa.Enum('github', 'zip', name='export_type'), nullable=False),
    sa.Column('destination', sa.Text(), nullable=True, comment='GitHub repo URL for github exports. null for zip.'),
    sa.Column('exported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_exports_funnel_id', 'exports', ['funnel_id'], unique=False)
    op.create_index('idx_exports_offer_id', 'exports', ['offer_id'], unique=False)
    op.create_index('idx_exports_user_id', 'exports', ['user_id'], unique=False)
    op.create_index('idx_exports_user_type', 'exports', ['user_id', 'export_type'], unique=False)
    op.create_table('funnel_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.UUID(), nullable=False, comment='One project per funnel — unique enforced.'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Denormalised for ownership checks'),
    sa.Column('files', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete Sandpack virtual file tree. ~80KB. node_modules excluded.'),
    sa.Column('boilerplate_version', sa.Text(), server_default='1.0.0', nullable=False, comment='Tracks which boilerplate version was used. For future migration tooling.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funnel_id')
    )
    op.create_index('idx_funnel_projects_funnel_id', 'funnel_projects', ['funnel_id'], unique=True)
    op.create_index('idx_funnel_projects_user_id', 'funnel_projects', ['user_id'], unique=False)
    op.create_table('funnel_steps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('funnel_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False, comment='1-based. Determines page sequence in the funnel.'),
    sa.Column('step_type', sa.Enum('presell', 'optin', 'waiting_list', 'launch_coming', 'quiz', 'vsl', 'sales', 'webinar_register', 'webinar_replay', 'order', 'order_bump', 'application', 'book_call', 'upsell', 'downsell', 'thankyou', 'members_area', 'bridge', 'offer', 'case_study', 'demo', 'custom', name='step_type'), nullable=False),
    sa.Column('custom_step_name', sa.Text(), nullable=True, comment='v2 — only populated when step_type = custom. User-defined label.'),
    sa.Column('status', sa.Enum('pending', 'generating', 'ready', 'error', name='step_status'), server_default='pending', nullable=False, comment='Updated independently per step as assembler generates each page component.'),
    sa.Column('slug', sa.Text(), nullable=False, comment='URL-safe route slug. e.g. vsl-page → /vsl-page in React Router.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funnel_steps_funnel_id', 'funnel_steps', ['funnel_id'], unique=False)
    op.create_index('idx_funnel_steps_order', 'funnel_steps', ['funnel_id', 'step_order'], unique=False)
    op.create_index('idx_funnel_steps_type_unique', 'funnel_steps', ['funnel_id', 'step_type'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_funnel_steps_type_unique', table_name='funnel_steps')
    op.drop_index('idx_funnel_steps_order', table_name='funnel_steps')
    op.drop_index('idx_funnel_steps_funnel_id', table_name='funnel_steps')
    op.drop_table('funnel_steps')
    op.drop_index('idx_funnel_projects_user_id', table_name='funnel_projects')
    op.drop_index('idx_funnel_projects_funnel_id', table_name='funnel_projects')
    op.drop_table('funnel_projects')
    op.drop_index('idx_exports_user_type', table_name='exports')
    op.drop_index('idx_exports_user_id', table_name='exports')
    op.drop_index('idx_exports_offer_id', table_name='exports')
    op.drop_index('idx_exports_funnel_id', table_name='exports')
    op.drop_table('exports')
    op.drop_index('idx_jobs_workflow_run_id', table_name='jobs')
    op.drop_index('idx_jobs_user_status', table_name='jobs')
    op.drop_index('idx_jobs_user_id', table_name='jobs')
    op.drop_index('idx_jobs_run_agent_unique', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_funnels_workflow_run_id', table_name='funnels')
    op.drop_index('idx_funnels_user_status', table_name='funnels')
    op.drop_index('idx_funnels_user_id', table_name='funnels')
    op.drop_index('idx_funnels_offer_id', table_name='funnels')
    op.drop_table('funnels')
    op.drop_index('idx_assets_workflow_run_id', table_name='assets')
    op.drop_index('idx_assets_user_id', table_name='assets')
    op.drop_index('idx_assets_offer_type', table_name='assets')
    op.drop_index('idx_assets_offer_id', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_agent_outputs_run_id', table_name='agent_outputs')
    op.drop_index('idx_agent_outputs_run_agent_version', table_name='agent_outputs')
    op.drop_index('idx_agent_outputs_offer_id', table_name='agent_outputs')
    op.drop_index('idx_agent_outputs_offer_agent', table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index('idx_workflow_runs_user_status', table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_user_id', table_name='workflow_runs')
    op.drop_index('idx_workflow_runs_offer_id', table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index('idx_workspace_members_user', table_name='workspace_members')
    op.drop_index('idx_workspace_members_unique', table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index('idx_offers_user_status', table_name='offers')
    op.drop_index('idx_offers_user_id', table_name='offers')
    op.drop_index('idx_offers_user_created', table_name='offers')
    op.drop_table('offers')
    op.drop_index('idx_workspaces_owner', table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('idx_integrations_user_provider_unique', table_name='integrations')
    op.drop_index('idx_integrations_user_id', table_name='integrations')
    op.drop_table('integrations')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_clerk_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
